/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.GiaoVien_DAO;
import Model.GiaoVien;
import Model.HocSinh;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh0
 */
public class fmGiaoVien extends javax.swing.JPanel {

    private final int THEM = 0;
    private final int SUA = 1;
    private final int XEMTT = 3;
    private boolean isedit = true;

    private GiaoVien_DAO dao = new GiaoVien_DAO();
    private List<GiaoVien> dsgv;
    private GiaoVien editgv;

    /**
     * Creates new form fmGiaoVien
     */
    public fmGiaoVien() {
        initComponents();
        loadcb();
        dsgv = dao.getALL();
        loadListtbl(dsgv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dl_addeditGV = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txt_maGV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tenGV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_addedit = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        rb_nu = new javax.swing.JRadioButton();
        rb_nam = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        cb_chuyenmon = new javax.swing.JComboBox<>();
        cb_trinhdo = new javax.swing.JComboBox<>();
        pop_glGV = new javax.swing.JPopupMenu();
        mn_suaGV = new javax.swing.JMenuItem();
        mn_xoaGV = new javax.swing.JMenuItem();
        mn_xemTT = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dsGV = new javax.swing.JTable();
        btn_openthemGV = new javax.swing.JButton();
        btn_opentkGV = new javax.swing.JButton();

        dl_addeditGV.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel1.setText("Mã GV");

        txt_maGV.setEditable(false);

        jLabel2.setText("Tên GV");

        jLabel3.setText("Giới tính");

        jLabel4.setText("SĐT");

        jLabel5.setText("Chuyên môn");

        jLabel6.setText("Trình độ");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("Ghi chú");

        btn_addedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btn_addedit.setText("Lưu");
        btn_addedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addeditActionPerformed(evt);
            }
        });

        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btn_huy.setText("Hủy");

        buttonGroup1.add(rb_nu);
        rb_nu.setText("Nữ");

        buttonGroup1.add(rb_nam);
        rb_nam.setSelected(true);
        rb_nam.setText("Nam");

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        jScrollPane2.setViewportView(txt_diachi);

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane3.setViewportView(txt_ghichu);

        cb_chuyenmon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_trinhdo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout dl_addeditGVLayout = new javax.swing.GroupLayout(dl_addeditGV.getContentPane());
        dl_addeditGV.getContentPane().setLayout(dl_addeditGVLayout);
        dl_addeditGVLayout.setHorizontalGroup(
            dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_addeditGVLayout.createSequentialGroup()
                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_addeditGVLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btn_addedit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_huy))
                    .addGroup(dl_addeditGVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dl_addeditGVLayout.createSequentialGroup()
                                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dl_addeditGVLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_tenGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_maGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(dl_addeditGVLayout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_sdt)
                                                .addComponent(cb_trinhdo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cb_chuyenmon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(dl_addeditGVLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(rb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        dl_addeditGVLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        dl_addeditGVLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_maGV, txt_sdt, txt_tenGV});

        dl_addeditGVLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, jLabel8});

        dl_addeditGVLayout.setVerticalGroup(
            dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_addeditGVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_addeditGVLayout.createSequentialGroup()
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_maGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_nam)
                                .addComponent(rb_nu))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dl_addeditGVLayout.createSequentialGroup()
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_chuyenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_trinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dl_addeditGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addedit)
                    .addComponent(btn_huy))
                .addGap(26, 26, 26))
        );

        dl_addeditGVLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        dl_addeditGVLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_maGV, txt_sdt, txt_tenGV});

        mn_suaGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        mn_suaGV.setText("Sửa TT GV");
        mn_suaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_suaGVActionPerformed(evt);
            }
        });
        pop_glGV.add(mn_suaGV);

        mn_xoaGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        mn_xoaGV.setText("Xóa TT GV");
        mn_xoaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xoaGVActionPerformed(evt);
            }
        });
        pop_glGV.add(mn_xoaGV);

        mn_xemTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xemdiem.png"))); // NOI18N
        mn_xemTT.setText("Xem TT GV");
        mn_xemTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xemTTActionPerformed(evt);
            }
        });
        pop_glGV.add(mn_xemTT);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách giáo viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

        tbl_dsGV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã GV", "Họ tên GV", "Giới tính", "SĐT", "Chuyên môn", "Trình độ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dsGV.setComponentPopupMenu(pop_glGV);
        jScrollPane1.setViewportView(tbl_dsGV);

        btn_openthemGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btn_openthemGV.setText("Thêm giáo viên");
        btn_openthemGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openthemGVActionPerformed(evt);
            }
        });

        btn_opentkGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xemdiem.png"))); // NOI18N
        btn_opentkGV.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_openthemGV, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_opentkGV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_opentkGV)
                    .addComponent(btn_openthemGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openthemGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openthemGVActionPerformed
        // TODO add your handling code here:
        openForm(THEM);
    }//GEN-LAST:event_btn_openthemGVActionPerformed

    private void btn_addeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addeditActionPerformed
        // TODO add your handling code here:\
        String maGV = txt_maGV.getText().trim();
        String HoTenGV = txt_tenGV.getText().trim();
        String gioitinh = "";
        if (rb_nam.isSelected()) {
            gioitinh = DataStatic.GTnam;
        } else {
            gioitinh = DataStatic.GTnu;
        }
        String Diachi = txt_diachi.getText().trim();
        String ChuyenMon = (String) cb_chuyenmon.getSelectedItem();
        String TrinhDo = (String) cb_trinhdo.getSelectedItem();
        String DienThoai = txt_sdt.getText().trim();
        String GhiChu = txt_ghichu.getText().trim();
        GiaoVien gv = new GiaoVien(maGV, HoTenGV, gioitinh, Diachi, ChuyenMon, TrinhDo, DienThoai, GhiChu);
        if (HoTenGV.length() == 0) {
            JOptionPane.showMessageDialog(fmGiaoVien.this, "Tên không dược để trống");
        } else {
            if (isedit) {
                int check = dao.Sua(gv);
                if (check == 0) {
                    dl_addeditGV.setVisible(false);
                    JOptionPane.showMessageDialog(fmGiaoVien.this, "Lưu không thành công");
                } else {
                    dl_addeditGV.setVisible(false);
                    dsgv = dao.getALL();
                    loadListtbl(dsgv);
                }
            } else {
                int check = dao.Them(gv);
                if (check == 0) {
                    dl_addeditGV.setVisible(false);
                    JOptionPane.showMessageDialog(fmGiaoVien.this, "Thêm không thành công");
                } else {
                    dl_addeditGV.setVisible(false);
                    dsgv = dao.getALL();
                    loadListtbl(dsgv);
                }
            }
        }

    }//GEN-LAST:event_btn_addeditActionPerformed

    private void mn_suaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_suaGVActionPerformed
        // TODO add your handling code here:
        int index = tbl_dsGV.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmGiaoVien.this, "Bạn chưa chọn giáo viên");
        } else {
            editgv = dsgv.get(index);
            openForm(SUA);
        }

    }//GEN-LAST:event_mn_suaGVActionPerformed

    private void mn_xoaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xoaGVActionPerformed
        // TODO add your handling code here:
        int index = tbl_dsGV.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmGiaoVien.this, "Bạn chưa chọn giáo viên");
        } else {
            int ck = JOptionPane.showConfirmDialog(fmGiaoVien.this, " Xóa TT GV : " + dsgv.get(index).getMaGV(), "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (ck == JOptionPane.YES_OPTION) {
                int check = dao.Xoa(dsgv.get(index));
                if (check == 0) {
                    JOptionPane.showMessageDialog(fmGiaoVien.this, "Xóa không thành công");
                } else {
                    dsgv = dao.getALL();
                    loadListtbl(dsgv);
                }
            }

        }
    }//GEN-LAST:event_mn_xoaGVActionPerformed

    private void mn_xemTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xemTTActionPerformed
        // TODO add your handling code here:
        int index = tbl_dsGV.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmGiaoVien.this, "Bạn chưa chọn giáo viên");
        } else {
            editgv = dsgv.get(index);
            openForm(XEMTT);
        }
    }//GEN-LAST:event_mn_xemTTActionPerformed

    private void openForm(int chedo) {
        if (chedo == THEM) {
            GiaoVien gv = new GiaoVien("", "", "", "", "", "", "", "");
            isedit = false;
            dl_addeditGV.setTitle("Thêm thông tin giáo viên");
            btn_addedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
            btn_addedit.setText("Thêm");
            btn_addedit.setEnabled(true);
            btn_huy.setEnabled(false);
            ghidulieu(gv);
            txt_maGV.setText(automaGV());

        } else if (chedo == SUA) {
            isedit = true;
            dl_addeditGV.setTitle("Sửa thông tin giáo viên");
            btn_addedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
            btn_addedit.setText("Lưu");
            btn_addedit.setEnabled(true);
            btn_huy.setEnabled(true);
            ghidulieu(editgv);

        } else if (chedo == XEMTT) {
            dl_addeditGV.setTitle("Thông tin giáo viên");
            btn_addedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
            btn_addedit.setText("Lưu");
            btn_addedit.setEnabled(false);
            btn_huy.setEnabled(false);
            ghidulieu(editgv);
        }
        dl_addeditGV.setSize(700, 350);
        dl_addeditGV.setLocationRelativeTo(null);
        dl_addeditGV.setResizable(false);
        dl_addeditGV.setVisible(true);
    }

    private void ghidulieu(GiaoVien gv) {
        txt_maGV.setText(gv.getMaGV());
        txt_tenGV.setText(gv.getHoTenGV());
        txt_sdt.setText(gv.getDienThoai());
        txt_ghichu.setText(gv.getGhiChu());
        txt_diachi.setText(gv.getDiachi());
        cb_chuyenmon.setSelectedItem(gv.getChuyenMon());
        cb_trinhdo.setSelectedItem(gv.getTrinhDo());
        if (gv.getGioitinh().compareTo(DataStatic.GTnam) == 0) {
            rb_nam.setSelected(true);
        } else {
            rb_nu.setSelected(true);
        }
    }

    private String automaGV() {
        String magv = "20220";
        magv = magv + String.valueOf(dao.getmaGVmax() + 1);
        return magv;
    }

    private void loadListtbl(List<GiaoVien> ds) {
        DefaultTableModel tblmodel = (DefaultTableModel) tbl_dsGV.getModel();
        tblmodel.setRowCount(0);
        if (ds == null) {

        } else {
            for (GiaoVien gv : ds) {
                tblmodel.addRow(new Object[]{gv.getMaGV(), gv.getHoTenGV(), gv.getGioitinh(), gv.getDienThoai(), gv.getChuyenMon(), gv.getTrinhDo()});
            }
        }
    }

    private void loadcb() {
        cb_trinhdo.removeAllItems();
        for(String td:DataStatic.TD){
            cb_trinhdo.addItem(td);
        }

        cb_chuyenmon.removeAllItems();
        for(String cm:DataStatic.CM){
            cb_chuyenmon.addItem(cm);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addedit;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_openthemGV;
    private javax.swing.JButton btn_opentkGV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_chuyenmon;
    private javax.swing.JComboBox<String> cb_trinhdo;
    private javax.swing.JDialog dl_addeditGV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem mn_suaGV;
    private javax.swing.JMenuItem mn_xemTT;
    private javax.swing.JMenuItem mn_xoaGV;
    private javax.swing.JPopupMenu pop_glGV;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tbl_dsGV;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JTextField txt_maGV;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenGV;
    // End of variables declaration//GEN-END:variables
}
