/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAO;
import DAO.DanToc_DAO;
import DAO.DienChinhSach_DAO;
import DAO.HocKi_DAO;
import DAO.HocSinh_DAO;
import DAO.TonGiao_DAO;
import Model.DanToc;
import Model.DienChinhSach;
import Model.HocSinh;
import Model.TonGiao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh0
 */
public class fmHocSinh extends javax.swing.JPanel {

    private MainView main;

    private HocSinh hssua;
    private List<HocSinh> dshs;
    private DAO dao;

    /**
     * Creates new form fmHocSinh
     */
    public fmHocSinh(MainView mainView) {
        this.main = mainView;
        initComponents();

        dao = new DanToc_DAO();
        DataStatic.dsDT = dao.getALL();
        dao = new DienChinhSach_DAO();
        DataStatic.dsDSC = dao.getALL();
        dao = new TonGiao_DAO();
        DataStatic.dsTG = dao.getALL();

        dao = new HocSinh_DAO();
        dshs = dao.getALL();
        loadListtbl(dshs);
        
        load_cb_dsc();
        load_cb_dt();
        load_cb_tongiao();
        load_cb_tt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dl_tthocsinh = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ttmahs = new javax.swing.JTextField();
        txt_ttsohieu = new javax.swing.JTextField();
        txt_hotenhs = new javax.swing.JTextField();
        cb_ttdantoc = new javax.swing.JComboBox<>();
        cb_tttongiao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_ttdsc = new javax.swing.JComboBox<>();
        txt_sdt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ghichu = new javax.swing.JTextArea();
        cb_trangthai = new javax.swing.JComboBox<>();
        btn_luu = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        rb_ttnam = new javax.swing.JRadioButton();
        rb_ttnu = new javax.swing.JRadioButton();
        dl_themhocsinh = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_tmahs = new javax.swing.JTextField();
        txt_tsohieu = new javax.swing.JTextField();
        txt_thotenhs = new javax.swing.JTextField();
        cb_tdantoc = new javax.swing.JComboBox<>();
        cb_ttongiao = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_tdsc = new javax.swing.JComboBox<>();
        txt_tsdt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_tdiachi = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_tghichu = new javax.swing.JTextArea();
        cb_ttrangthai = new javax.swing.JComboBox<>();
        btn_them = new javax.swing.JButton();
        rb_tnam = new javax.swing.JRadioButton();
        rb_tnu = new javax.swing.JRadioButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mn_xemtths = new javax.swing.JMenuItem();
        mn_suatths = new javax.swing.JMenuItem();
        mn_xoahs = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hocsinh = new javax.swing.JTable();
        btn_openthem = new javax.swing.JButton();

        dl_tthocsinh.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dl_tthocsinh.setTitle("Thông tin học sinh");
        dl_tthocsinh.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel1.setText("Mã HS");

        jLabel2.setText("Số hiệu");

        jLabel3.setText("Họ tên HS:");

        jLabel4.setText("Dân tộc:");

        jLabel5.setText("Tôn giáo:");

        txt_ttmahs.setEditable(false);

        cb_ttdantoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_tttongiao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Diện CS:");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Địa chỉ");

        jLabel9.setText("ĐIện thoại");

        jLabel10.setText("Ghi chú");

        cb_ttdsc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Trạng thái:");

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        jScrollPane2.setViewportView(txt_diachi);

        txt_ghichu.setColumns(20);
        txt_ghichu.setRows(5);
        jScrollPane3.setViewportView(txt_ghichu);

        cb_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        btn_luu.setText("Lưu thông tin");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btnhuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnhuy.setText("Hủy");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_ttnam);
        rb_ttnam.setSelected(true);
        rb_ttnam.setText("Nam");

        buttonGroup1.add(rb_ttnu);
        rb_ttnu.setText("Nữ");

        javax.swing.GroupLayout dl_tthocsinhLayout = new javax.swing.GroupLayout(dl_tthocsinh.getContentPane());
        dl_tthocsinh.getContentPane().setLayout(dl_tthocsinhLayout);
        dl_tthocsinhLayout.setHorizontalGroup(
            dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ttmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ttsohieu))
                            .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_ttnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_ttnu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_ttdsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_tttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_hotenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_ttdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cb_trangthai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btn_luu)
                        .addGap(18, 18, 18)
                        .addComponent(btnhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        dl_tthocsinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        dl_tthocsinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_ttdantoc, cb_ttdsc, cb_tttongiao, txt_hotenhs, txt_sdt, txt_ttmahs, txt_ttsohieu});

        dl_tthocsinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel6, jLabel7, jLabel8, jLabel9});

        dl_tthocsinhLayout.setVerticalGroup(
            dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_ttmahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ttsohieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hotenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_tthocsinhLayout.createSequentialGroup()
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_ttdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_tttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_ttdsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)
                                .addComponent(cb_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rb_ttnam))
                            .addComponent(rb_ttnu))
                        .addGap(18, 18, 18)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dl_tthocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_luu)
                            .addComponent(btnhuy)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        dl_tthocsinhLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        dl_tthocsinhLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel6, jLabel7, jLabel8, jLabel9});

        dl_themhocsinh.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dl_themhocsinh.setTitle("Thêm học sinh");
        dl_themhocsinh.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel12.setText("Mã HS");

        jLabel13.setText("Số hiệu");

        jLabel14.setText("Họ tên HS:");

        jLabel15.setText("Dân tộc:");

        jLabel16.setText("Tôn giáo:");

        txt_tmahs.setEditable(false);

        cb_tdantoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb_ttongiao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Diện CS:");

        jLabel18.setText("Giới tính");

        jLabel19.setText("Địa chỉ");

        jLabel20.setText("ĐIện thoại");

        jLabel21.setText("Ghi chú");

        cb_tdsc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setText("Trạng thái:");

        txt_tdiachi.setColumns(20);
        txt_tdiachi.setRows(5);
        jScrollPane4.setViewportView(txt_tdiachi);

        txt_tghichu.setColumns(20);
        txt_tghichu.setRows(5);
        jScrollPane5.setViewportView(txt_tghichu);

        cb_ttrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btn_them.setText("Thêm học sinh");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb_tnam);
        rb_tnam.setSelected(true);
        rb_tnam.setText("Nam");

        buttonGroup2.add(rb_tnu);
        rb_tnu.setText("Nữ");

        javax.swing.GroupLayout dl_themhocsinhLayout = new javax.swing.GroupLayout(dl_themhocsinh.getContentPane());
        dl_themhocsinh.getContentPane().setLayout(dl_themhocsinhLayout);
        dl_themhocsinhLayout.setHorizontalGroup(
            dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tsohieu, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_tdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_tnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_tnu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(18, 18, 18)
                                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                                .addComponent(cb_tdsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22))
                                            .addComponent(cb_ttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_thotenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(cb_ttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        dl_themhocsinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jLabel22});

        dl_themhocsinhLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_tdantoc, cb_tdsc, cb_ttongiao, txt_thotenhs, txt_tmahs, txt_tsdt, txt_tsohieu});

        dl_themhocsinhLayout.setVerticalGroup(
            dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_tmahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_tsohieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_thotenhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cb_tdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cb_ttongiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dl_themhocsinhLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cb_tdsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cb_ttrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rb_tnam)
                    .addComponent(rb_tnu))
                .addGap(18, 18, 18)
                .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dl_themhocsinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_them))
                    .addComponent(jLabel20))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        dl_themhocsinhLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jLabel22});

        mn_xemtths.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xemdiem.png"))); // NOI18N
        mn_xemtths.setText("Xem thông tin");
        mn_xemtths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xemtthsActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mn_xemtths);

        mn_suatths.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        mn_suatths.setText("Sửa thông tin");
        mn_suatths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_suatthsActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mn_suatths);

        mn_xoahs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        mn_xoahs.setText("Xóa thông tin ");
        mn_xoahs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xoahsActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mn_xoahs);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách học sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        jScrollPane1.setComponentPopupMenu(jPopupMenu1);

        tbl_hocsinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã học sinh", "Số hiệu", "Tên học sinh", "Giới tính", "SĐT", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hocsinh.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbl_hocsinh);

        btn_openthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btn_openthem.setText("THÊM HỌC SINH");
        btn_openthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_openthem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(btn_openthem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openthemActionPerformed

        dl_themhocsinh.setSize(652, 400);
        dl_themhocsinh.setLocationRelativeTo(null);
        dl_themhocsinh.setResizable(false);
        reset_dlthemhs();
        String mahs = automaHS();
        txt_tmahs.setText(mahs);
        txt_tsohieu.setText(mahs);
        dl_themhocsinh.setVisible(true);
        
    }//GEN-LAST:event_btn_openthemActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String MaHS = txt_tmahs.getText().trim();
        String SoHieu = txt_tsohieu.getText().trim();
        String HotenHS = txt_thotenhs.getText().trim();
        String MaDanToc = DataStatic.dsDT.get(cb_tdantoc.getSelectedIndex()).getMaDanToc();
        String MaChinhSach = DataStatic.dsDSC.get(cb_tdsc.getSelectedIndex()).getMaChinhsach();
        String MaTonGiao = DataStatic.dsTG.get(cb_ttongiao.getSelectedIndex()).getMaTonGiao();
        String GioiTinh ="";
        if(rb_tnam.isSelected()){
            GioiTinh = DataStatic.GTnam;
        }else{
            GioiTinh = DataStatic.GTnu;
        }
        String DiaChi = txt_tdiachi.getText().trim();
        String DienThoai = txt_tsdt.getText().trim();
        String GhiChu = txt_tghichu.getText().trim();
        String TrangThai = (String) cb_ttrangthai.getSelectedItem();
        HocSinh hs = new HocSinh(MaHS, SoHieu, HotenHS, MaDanToc, MaChinhSach, MaTonGiao, GioiTinh, DiaChi, DienThoai, GhiChu, TrangThai);
        dao = new HocSinh_DAO();
        int kt = dao.Them(hs);
        if(kt ==1){
            
            dshs = dao.getALL();
            loadListtbl(dshs);
            dl_themhocsinh.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(fmHocSinh.this, "Thêm không thành công");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void mn_xemtthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xemtthsActionPerformed
        // TODO add your handling code here:
        hssua = null;
        int index = tbl_hocsinh.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmHocSinh.this, "Bạn chưa chọn học sinh");
        } else {
            hssua = dshs.get(index);
            open_suaTT(false);
        }
    }//GEN-LAST:event_mn_xemtthsActionPerformed

    private void mn_suatthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_suatthsActionPerformed
        // TODO add your handling code here:
        hssua = null;
        int index = tbl_hocsinh.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmHocSinh.this, "Bạn chưa chọn học sinh");
        } else {
            hssua = dshs.get(index);
            open_suaTT(true);
        }
    }//GEN-LAST:event_mn_suatthsActionPerformed

    private void mn_xoahsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xoahsActionPerformed
        // TODO add your handling code here:
        int index = tbl_hocsinh.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(fmHocSinh.this, "Bạn chưa chọn học sinh");
        } else {
            int ck = JOptionPane.showConfirmDialog(jScrollPane5, " Xóa học sinh : " + dshs.get(index).getMaHS(), "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (ck == JOptionPane.YES_OPTION) {

                dao = new HocSinh_DAO();
                int kt = dao.Xoa(dshs.get(index));
                if (kt == 1) {
                    dshs.remove(index);
                    loadListtbl(dshs);
                } else {
                    JOptionPane.showMessageDialog(fmHocSinh.this, "Xóa không thành công");
                }
            }
        }
    }//GEN-LAST:event_mn_xoahsActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String MaHS = txt_ttmahs.getText().trim();
        String SoHieu = txt_ttsohieu.getText().trim();
        String HotenHS = txt_hotenhs.getText().trim();
        String MaDanToc = DataStatic.dsDT.get(cb_ttdantoc.getSelectedIndex()).getMaDanToc();
        String MaChinhSach = DataStatic.dsDSC.get(cb_ttdsc.getSelectedIndex()).getMaChinhsach();
        String MaTonGiao = DataStatic.dsTG.get(cb_tttongiao.getSelectedIndex()).getMaTonGiao();
        String GioiTinh ="";
        if(rb_ttnam.isSelected()){
            GioiTinh = DataStatic.GTnam;
        }else{
            GioiTinh = DataStatic.GTnu;
        }
        String DiaChi = txt_diachi.getText().trim();
        String DienThoai = txt_sdt.getText().trim();
        String GhiChu = txt_ghichu.getText().trim();
        String TrangThai = (String) cb_trangthai.getSelectedItem();
        HocSinh hs = new HocSinh(MaHS, SoHieu, HotenHS, MaDanToc, MaChinhSach, MaTonGiao, GioiTinh, DiaChi, DienThoai, GhiChu, TrangThai);
        dao = new HocSinh_DAO();
        int kt = dao.Sua(hs);
        if(kt ==1){
            
            dshs = dao.getALL();
            loadListtbl(dshs);
            dl_tthocsinh.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(fmHocSinh.this, "Lưu không thành công");
        }
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
        // TODO add your handling code here:
        setTextform(hssua);
    }//GEN-LAST:event_btnhuyActionPerformed

    private void loadListtbl(List<HocSinh> ds) {
        DefaultTableModel tblmodel = (DefaultTableModel) tbl_hocsinh.getModel();
        tblmodel.setRowCount(0);
        if (ds == null) {

        } else {
            for (int i = 0; i < ds.size(); i++) {
                HocSinh hs = ds.get(i);
                tblmodel.addRow(new Object[]{hs.getMaHS(),hs.getSoHieu(),hs.getHotenHS()
                        ,hs.getGioiTinh(),hs.getDienThoai(),hs.getTrangThai()});
            }
        }
    }

    private void open_suaTT(boolean issua) {
        if (issua) {
            dl_tthocsinh.setSize(700, 450);
            dl_tthocsinh.setLocationRelativeTo(null);
            dl_tthocsinh.setResizable(false);
            dl_tthocsinh.setTitle("Chỉnh sủa thông tin học sinh");
            btn_luu.setEnabled(true);
            btnhuy.setEnabled(true);
            setTextform(hssua);
            dl_tthocsinh.setVisible(true);
            
        } else {
            dl_tthocsinh.setSize(700, 450);
            dl_tthocsinh.setLocationRelativeTo(null);
            dl_tthocsinh.setResizable(false);
            dl_tthocsinh.setTitle("Thông tin học sinh");
            btn_luu.setEnabled(false);
            btnhuy.setEnabled(false);
            setTextform(hssua);
            dl_tthocsinh.setVisible(true);
            
            
        }

    }

    private void setTextform(HocSinh hs) {
        txt_ttmahs.setText(hs.getMaHS());
        txt_ttsohieu.setText(hs.getSoHieu());
        txt_hotenhs.setText(hs.getHotenHS());
        txt_sdt.setText(hs.getDienThoai());
        txt_diachi.setText(hs.getDiaChi());
        txt_ghichu.setText(hs.getGhiChu());
        cb_ttdantoc.setSelectedItem(DanToc.getTenDT(hs.getMaDanToc(), DataStatic.dsDT));
        cb_ttdsc.setSelectedItem(DienChinhSach.getTen(hs.getMaChinhSach(), DataStatic.dsDSC));
        cb_tttongiao.setSelectedItem(TonGiao.getTen(hs.getMaTonGiao(), DataStatic.dsTG));
        if(hs.getGioiTinh().compareTo(DataStatic.GTnam)==0){
            rb_ttnam.setSelected(true);
        }else{
            rb_ttnu.setSelected(true);
        }
        cb_trangthai.setSelectedItem(hs.getTrangThai());
        
    }

    private void load_cb_dt() {
        cb_ttdantoc.removeAllItems();
        cb_tdantoc.removeAllItems();
        for (DanToc dt : DataStatic.dsDT) {
            cb_ttdantoc.addItem(dt.getDanToc());
            cb_tdantoc.addItem(dt.getDanToc());
        }
    }

    private void load_cb_dsc() {
        cb_tdsc.removeAllItems();
        cb_ttdsc.removeAllItems();
        for (DienChinhSach dsc : DataStatic.dsDSC) {
            cb_tdsc.addItem(dsc.getTenChinhSach());
            cb_ttdsc.addItem(dsc.getTenChinhSach());
        }
    }
    
    private void load_cb_tongiao() {
        cb_ttongiao.removeAllItems();
        cb_tttongiao.removeAllItems();
        for (TonGiao tg : DataStatic.dsTG) {
            cb_ttongiao.addItem(tg.getTonGiao());
            cb_tttongiao.addItem(tg.getTonGiao());
        }
    }

    private void load_cb_tt() {
        cb_trangthai.removeAllItems();
        cb_ttrangthai.removeAllItems();
        for(String tths:DataStatic.TT_HS){
            cb_trangthai.addItem(tths);
            cb_ttrangthai.addItem(tths);
        }
    }

    private String automaHS(){
        HocSinh_DAO daohs = new HocSinh_DAO();
        int stt = daohs.getmaHSmax(main.getMaNH())+1;
        String ma = main.getMaNH()+String.valueOf(stt);
        return ma;
    }
    
    private void reset_dlthemhs(){
        txt_tmahs.setText("");
        txt_tsohieu.setText("");
        txt_thotenhs.setText("");
        txt_tsdt.setText("");
        txt_tdiachi.setText("");
        txt_tghichu.setText("");
        cb_tdantoc.setSelectedIndex(0);
        cb_tdsc.setSelectedIndex(0);
        cb_ttongiao.setSelectedIndex(0);
        cb_ttrangthai.setSelectedIndex(0);
        rb_tnam.setSelected(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_openthem;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btnhuy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_tdantoc;
    private javax.swing.JComboBox<String> cb_tdsc;
    private javax.swing.JComboBox<String> cb_trangthai;
    private javax.swing.JComboBox<String> cb_ttdantoc;
    private javax.swing.JComboBox<String> cb_ttdsc;
    private javax.swing.JComboBox<String> cb_ttongiao;
    private javax.swing.JComboBox<String> cb_ttrangthai;
    private javax.swing.JComboBox<String> cb_tttongiao;
    private javax.swing.JDialog dl_themhocsinh;
    private javax.swing.JDialog dl_tthocsinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenuItem mn_suatths;
    private javax.swing.JMenuItem mn_xemtths;
    private javax.swing.JMenuItem mn_xoahs;
    private javax.swing.JRadioButton rb_tnam;
    private javax.swing.JRadioButton rb_tnu;
    private javax.swing.JRadioButton rb_ttnam;
    private javax.swing.JRadioButton rb_ttnu;
    private javax.swing.JTable tbl_hocsinh;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextArea txt_ghichu;
    private javax.swing.JTextField txt_hotenhs;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextArea txt_tdiachi;
    private javax.swing.JTextArea txt_tghichu;
    private javax.swing.JTextField txt_thotenhs;
    private javax.swing.JTextField txt_tmahs;
    private javax.swing.JTextField txt_tsdt;
    private javax.swing.JTextField txt_tsohieu;
    private javax.swing.JTextField txt_ttmahs;
    private javax.swing.JTextField txt_ttsohieu;
    // End of variables declaration//GEN-END:variables
}
