/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.Another_DAO;
import Model.another.ThongkeHK;
import Model.another.ThongkeHL;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh0
 */
public class fmThongKe extends javax.swing.JPanel {
    private MainView mainView;
    private Another_DAO dao = new Another_DAO();
    /**
     * Creates new form fmThongKe
     */
    public fmThongKe(MainView mainView) {
        this.mainView = mainView;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tkhocluc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tkhanhkiem = new javax.swing.JTable();
        rd_hk = new javax.swing.JRadioButton();
        rd_canam = new javax.swing.JRadioButton();
        btn_capnhat = new javax.swing.JButton();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống kê học lực mỗi lớp "));

        tbl_tkhocluc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên lớp ", "Tổng số", "Giỏi", "Khá", "Trung bình", "Yếu", "Kém"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tkhocluc);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống kê hạnh kiểm mỗi lớp"));

        tbl_tkhanhkiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên lớp", "Tổng số", "Tốt", "Khá", "Trung bình", "Yếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_tkhanhkiem);

        buttonGroup1.add(rd_hk);
        rd_hk.setSelected(true);
        rd_hk.setText("Theo học kì");
        rd_hk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_hkActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_canam);
        rd_canam.setText("Cả năm học");

        btn_capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd_hk)
                    .addComponent(rd_canam))
                .addGap(81, 81, 81)
                .addComponent(btn_capnhat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rd_hk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(rd_canam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_capnhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    }// </editor-fold>//GEN-END:initComponents

    private void rd_hkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_hkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_hkActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
        boolean canam = false;
        if (rd_canam.isSelected()){
            canam = true;
        }else{
            canam = false;
        }
        String maNH = mainView.getMaNH();
        String maHK = mainView.getmaHK();
        List<ThongkeHL> dsHL = dao.thongkeHLs(maNH, maHK, canam);
        List<ThongkeHK> dsHK = dao.dsThongkeHK(maNH, maHK, canam);
        DefaultTableModel tblmodel = (DefaultTableModel) tbl_tkhocluc.getModel();
        tblmodel.setRowCount(0);
        for (ThongkeHL thongkeHL : dsHL) {
            tblmodel.addRow(new Object[]{
                    thongkeHL.tenlop,thongkeHL.tongso,thongkeHL.gioi,thongkeHL.kha,thongkeHL.trungbinh,thongkeHL.yeu,thongkeHL.kem
                });
        }
        tblmodel = (DefaultTableModel) tbl_tkhanhkiem.getModel();
        tblmodel.setRowCount(0);
        for (ThongkeHK thongkeHK : dsHK) {
            tblmodel.addRow(new Object[]{
                    thongkeHK.tenlop,thongkeHK.tongso,thongkeHK.tot,thongkeHK.kha,thongkeHK.trungbinh,thongkeHK.yeu
                });
        }
    }//GEN-LAST:event_btn_capnhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd_canam;
    private javax.swing.JRadioButton rd_hk;
    private javax.swing.JTable tbl_tkhanhkiem;
    private javax.swing.JTable tbl_tkhocluc;
    // End of variables declaration//GEN-END:variables
}
