/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.XepLop_DAO;
import Model.HocKi;
import Model.HocSinh;
import Model.HocSinhLop;
import Model.Lop;
import Model.NamHoc;
import java.awt.Color;
import java.awt.Font;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minh0
 */
public class fmXepLop extends javax.swing.JPanel {

    private MainView main;
    private List<HocSinh> dstk;
    private List<HocSinh> dslop;
    private XepLop_DAO dao = new XepLop_DAO();

    /**
     * Creates new form fmXepLop
     */
    public fmXepLop(MainView mainView) {
        this.main = mainView;
        initComponents();
        loadcb_NH();
        loadcb_HK();
        loadcb_lop();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_tìmkiemHS = new javax.swing.JDialog();
        rb_tklop = new javax.swing.JRadioButton();
        cb_tklop = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cb_tknamhoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_tkhocki = new javax.swing.JComboBox<>();
        btn_timkiem = new javax.swing.JButton();
        rb_hsnhaphoc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        rb_tang = new javax.swing.JRadioButton();
        rb_giam = new javax.swing.JRadioButton();
        ck_loaiHS = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pop_dstk = new javax.swing.JPopupMenu();
        mn_themdstk = new javax.swing.JMenuItem();
        mn_themtoanbo = new javax.swing.JMenuItem();
        mn_xoadstk = new javax.swing.JMenuItem();
        pop_dslop = new javax.swing.JPopupMenu();
        mn_xoa_dslop = new javax.swing.JMenuItem();
        mn_refresh = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btn_openTK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dstk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_dslop = new javax.swing.JTable();
        cb_lop_moi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jl_tongHS_dstk = new javax.swing.JLabel();
        jl_tongHS_dslh = new javax.swing.JLabel();

        jd_tìmkiemHS.setTitle("Tìm kiếm học sinh");
        jd_tìmkiemHS.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        buttonGroup1.add(rb_tklop);
        rb_tklop.setSelected(true);
        rb_tklop.setText("Lớp: ");

        cb_tklop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Năm học:");

        cb_tknamhoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Học kì:");

        cb_tkhocki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xemdiem.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_hsnhaphoc);
        rb_hsnhaphoc.setText("Học sinh nhập học");

        jLabel2.setText("Tìm kiếm theo");

        jLabel5.setText("Sắp xếp theo");

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Theo tên học sinh");

        buttonGroup2.add(rb_tang);
        rb_tang.setSelected(true);
        rb_tang.setText("Tăng dần");

        buttonGroup2.add(rb_giam);
        rb_giam.setText("Giảm dần");

        ck_loaiHS.setText("Loai bo hoc sinh da xep lop trong nam hoc --- hoc ky1");

        javax.swing.GroupLayout jd_tìmkiemHSLayout = new javax.swing.GroupLayout(jd_tìmkiemHS.getContentPane());
        jd_tìmkiemHS.getContentPane().setLayout(jd_tìmkiemHSLayout);
        jd_tìmkiemHSLayout.setHorizontalGroup(
            jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                        .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                            .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rb_hsnhaphoc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                                    .addComponent(rb_tklop, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cb_tklop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(162, 162, 162))
                                        .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                            .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(126, 126, 126))
                                                .addComponent(cb_tknamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cb_tkhocki, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_tìmkiemHSLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_tang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_giam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_tìmkiemHSLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ck_loaiHS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jd_tìmkiemHSLayout.setVerticalGroup(
            jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tìmkiemHSLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_tkhocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cb_tknamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_tklop)
                    .addComponent(cb_tklop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rb_hsnhaphoc)
                .addGap(10, 10, 10)
                .addComponent(ck_loaiHS)
                .addGap(18, 18, 18)
                .addGroup(jd_tìmkiemHSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_tang)
                    .addComponent(rb_giam))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiem)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mn_themdstk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        mn_themdstk.setText("Thêm vào danh sách lớp học");
        mn_themdstk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_themdstkActionPerformed(evt);
            }
        });
        pop_dstk.add(mn_themdstk);

        mn_themtoanbo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        mn_themtoanbo.setText("Thêm toàn bộ vào  ds lớp");
        mn_themtoanbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_themtoanboActionPerformed(evt);
            }
        });
        pop_dstk.add(mn_themtoanbo);

        mn_xoadstk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        mn_xoadstk.setText("Xóa khỏi danh sách");
        mn_xoadstk.setToolTipText("Xóa khỏi danh sách");
        mn_xoadstk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xoadstkActionPerformed(evt);
            }
        });
        pop_dstk.add(mn_xoadstk);

        mn_xoa_dslop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        mn_xoa_dslop.setText("Xóa khỏi danh sách lớp");
        mn_xoa_dslop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_xoa_dslopActionPerformed(evt);
            }
        });
        pop_dslop.add(mn_xoa_dslop);

        mn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        mn_refresh.setText("Cập nhật danh sách");
        mn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_refreshActionPerformed(evt);
            }
        });
        pop_dslop.add(mn_refresh);

        btn_openTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xemdiem.png"))); // NOI18N
        btn_openTK.setText("Tìm kiếm học sinh");
        btn_openTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openTKActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách học sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

        tbl_dstk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã học sinh", "Họ tên HS", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dstk.setComponentPopupMenu(pop_dstk);
        jScrollPane1.setViewportView(tbl_dstk);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách học sinh có trong lớp học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10), new java.awt.Color(255, 0, 0))); // NOI18N

        tbl_dslop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã HS", "Họ tên HS", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dslop.setComponentPopupMenu(pop_dslop);
        jScrollPane2.setViewportView(tbl_dslop);

        cb_lop_moi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Lớp :");

        jl_tongHS_dstk.setText("Tổng số học sinh");

        jl_tongHS_dslh.setText("Tổng số học sinh: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_openTK)
                            .addComponent(jl_tongHS_dstk, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cb_lop_moi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(379, 379, 379))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_tongHS_dslh, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_lop_moi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_openTK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tongHS_dslh)
                    .addComponent(jl_tongHS_dstk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_openTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openTKActionPerformed
        // TODO add your handling code here:
        jd_tìmkiemHS.setSize(400, 350);
        jd_tìmkiemHS.setLocationRelativeTo(null);
        jd_tìmkiemHS.setResizable(false);
        ck_loaiHS.setText("Loại những học sinh đã xếp lớp trong năm học: "
                + NamHoc.getNamHoc(main.getMaNH(), DataStatic.dsNH) + " " + HocKi.getTen(main.getmaHK(), DataStatic.dsHK));
        jd_tìmkiemHS.setVisible(true);
    }//GEN-LAST:event_btn_openTKActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        load_dsHS_tk();
        loadlist_tbl(tbl_dstk, dstk);

        jd_tìmkiemHS.setVisible(false);
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void mn_themdstkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_themdstkActionPerformed
        // TODO add your handling code here:
        String maNamHoc = main.getMaNH();
        String maHK = main.getmaHK();
        String malop = DataStatic.dsLop.get(cb_lop_moi.getSelectedIndex()).getMaLop();
        int[] spam = tbl_dstk.getSelectedRows();
        int count =0;
        if (spam.length == 0) {

        } else {
            List<HocSinh> dsremove = new ArrayList<>();
            for (int i = 0; i < spam.length; i++) {
                HocSinhLop hsl = new HocSinhLop(dstk.get(spam[i]).getMaHS(), maNamHoc, maHK, malop);
                int check = dao.Them(hsl);
                if (check == 1) {
                    dsremove.add(dstk.get(spam[i]));
                }
            }
            dstk.removeAll(dsremove);
            load_dsHSlop();
            loadlist_tbl(tbl_dslop, dslop);
            loadlist_tbl(tbl_dstk, dstk);
        }
        
    }//GEN-LAST:event_mn_themdstkActionPerformed

    private void mn_themtoanboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_themtoanboActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<dstk.size();i++){
            
        }
    }//GEN-LAST:event_mn_themtoanboActionPerformed

    private void mn_xoadstkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xoadstkActionPerformed
        // TODO add your handling code here:
        int[] spam = tbl_dstk.getSelectedRows();
        if (spam.length == 0) {

        } else {
            for (int i = 0; i < spam.length; i++) {
                
                dstk.remove(spam[i]);
            }
        }
        
    }//GEN-LAST:event_mn_xoadstkActionPerformed

    private void mn_xoa_dslopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_xoa_dslopActionPerformed
        // TODO add your handling code here:
        String maNamHoc = main.getMaNH();
        String maHK = main.getmaHK();
        String malop = DataStatic.dsLop.get(cb_lop_moi.getSelectedIndex()).getMaLop();
        int[] spam = tbl_dslop.getSelectedRows();
        if (spam.length == 0) {

        } else {
            List<HocSinh> dsremove = new ArrayList<>();
            for (int i = 0; i < spam.length; i++) {
                HocSinhLop hsl = new HocSinhLop(dslop.get(spam[i]).getMaHS(), maNamHoc, maHK, malop);
                int check = dao.Xoa(hsl);
                if (check == 1) {
                    dsremove.add(dslop.get(spam[i]));
                }
            }
            dslop.removeAll(dsremove);
            load_dsHSlop();
            loadlist_tbl(tbl_dslop, dslop);
            loadlist_tbl(tbl_dstk, dstk);
        }

    }//GEN-LAST:event_mn_xoa_dslopActionPerformed

    private void mn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_refreshActionPerformed
        // TODO add your handling code here:
        load_dsHSlop();
        loadlist_tbl(tbl_dslop, dslop);
    }//GEN-LAST:event_mn_refreshActionPerformed

    public void loadcb_NH() {
        cb_tknamhoc.removeAllItems();
        for (NamHoc nh : DataStatic.dsNH) {
            cb_tknamhoc.addItem(nh.getNamHoc());
        }
    }

    public void loadcb_HK() {
        cb_tkhocki.removeAllItems();
        for (HocKi nh : DataStatic.dsHK) {
            cb_tkhocki.addItem(nh.getHK());
        }
    }

    public void loadcb_lop() {
        cb_tklop.removeAllItems();
        cb_lop_moi.removeAllItems();
        for (Lop nh : DataStatic.dsLop) {
            cb_tklop.addItem(nh.getTenLop());
            cb_lop_moi.addItem(nh.getTenLop());
        }
    }

    private void loadlist_tbl(JTable tbl, List<HocSinh> ds) {
        DefaultTableModel tblmodel = (DefaultTableModel) tbl.getModel();
        tblmodel.setRowCount(0);
        if (ds == null||ds.isEmpty()) {

        } else {
            for (HocSinh hs : ds) {
                tblmodel.addRow(new Object[]{hs.getMaHS(), hs.getHotenHS(), hs.getTrangThai()});
            }
        }
    }

    private void load_dsHS_tk() {
        boolean hschuacolop = rb_hsnhaphoc.isSelected();
        String maNamHoc = DataStatic.dsNH.get(cb_tknamhoc.getSelectedIndex()).getMaNH();
        String maHK = DataStatic.dsHK.get(cb_tkhocki.getSelectedIndex()).getMaHK();
        String malop = DataStatic.dsLop.get(cb_tklop.getSelectedIndex()).getMaLop();
        boolean tangdan = rb_tang.isSelected();
        boolean loaiHS = ck_loaiHS.isSelected();
        String maNamHoc2 = main.getMaNH();
        String maHK2 = main.getmaHK();
        dstk = dao.tkHSlop(hschuacolop, maNamHoc, maHK, malop, tangdan, loaiHS, maNamHoc2, maHK2);
        String title = "";
        if (hschuacolop) {
            title = "Danh sách học sinh nhập học chưa xếp lớp";

        } else {
            if (loaiHS) {
                title = "Danh sách học sinh lớp "
                        + Lop.getTenLop(malop, DataStatic.dsLop)
                        + " năm học " + NamHoc.getNamHoc(maNamHoc, DataStatic.dsNH) + " "
                        + HocKi.getTen(maHK, DataStatic.dsHK);
            } else {
                title = "Danh sách học sinh lớp "
                        + Lop.getTenLop(malop, DataStatic.dsLop)
                        + " năm học " + NamHoc.getNamHoc(maNamHoc, DataStatic.dsNH) + " "
                        + HocKi.getTen(maHK, DataStatic.dsHK);
            }

        }
        jl_tongHS_dstk.setText("Tổng số học sinh" + dstk.size());
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(null,
                title,
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", 2, 10),
                new Color(255, 0, 0)));
    }

    public void load_dsHSlop() {
        boolean hschuacolop = false;
        String maNamHoc = main.getMaNH();
        String maHK = main.getmaHK();
        String malop = DataStatic.dsLop.get(cb_lop_moi.getSelectedIndex()).getMaLop();
        boolean tangdan = true;
        boolean loaiHS = false;
        String maNamHoc2 = main.getMaNH();
        String maHK2 = main.getmaHK();
        dslop = dao.tkHSlop(hschuacolop, maNamHoc, maHK, malop, tangdan, loaiHS, maNamHoc2, maHK2);
        jScrollPane2.setBorder(BorderFactory.createTitledBorder(null,
                "Danh sách học sinh lớp " + Lop.getTenLop(malop, DataStatic.dsLop) + " năm học " + NamHoc.getNamHoc(maNamHoc, DataStatic.dsNH) + " " + HocKi.getTen(maHK, DataStatic.dsHK),
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", 2, 10),
                new Color(255, 0, 0)));
        jl_tongHS_dslh.setText("Tổng số học sinh: " + dslop.size());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_openTK;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb_lop_moi;
    private javax.swing.JComboBox<String> cb_tkhocki;
    private javax.swing.JComboBox<String> cb_tklop;
    private javax.swing.JComboBox<String> cb_tknamhoc;
    private javax.swing.JCheckBox ck_loaiHS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_tìmkiemHS;
    private javax.swing.JLabel jl_tongHS_dslh;
    private javax.swing.JLabel jl_tongHS_dstk;
    private javax.swing.JMenuItem mn_refresh;
    private javax.swing.JMenuItem mn_themdstk;
    private javax.swing.JMenuItem mn_themtoanbo;
    private javax.swing.JMenuItem mn_xoa_dslop;
    private javax.swing.JMenuItem mn_xoadstk;
    private javax.swing.JPopupMenu pop_dslop;
    private javax.swing.JPopupMenu pop_dstk;
    private javax.swing.JRadioButton rb_giam;
    private javax.swing.JRadioButton rb_hsnhaphoc;
    private javax.swing.JRadioButton rb_tang;
    private javax.swing.JRadioButton rb_tklop;
    private javax.swing.JTable tbl_dslop;
    private javax.swing.JTable tbl_dstk;
    // End of variables declaration//GEN-END:variables
}
